import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gabriel Milanez | Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <h1 className="text-orange-500">Portfolio</h1>
      </div>
    </div>
  );
}
