/* eslint-disable @next/next/no-page-custom-font */
import About from "@/components/About";
import CallToAction from "@/components/CallToAction";
import Clients from "@/components/Clients";
import Contact from "@/components/Contact";
import ContactWithForm from "@/components/ContactWithForm";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import Projects from "@/components/Projects";
import Services from "@/components/Services";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gabriel Milanez | Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navbar />
      <div className="mt-16 max-w-[1240px] m-auto flex flex-col items-center">
        <Hero />
        <About />
        <Services />
        <Projects />
        <Clients />
        <CallToAction />
        <Contact />
        {/* <ContactWithForm /> */}
      </div>
      <Footer />
    </div>
  );
}
